databases:
  - name: specialwash-db
    plan: free

services:
  - type: web
    name: specialwash-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt || pip install -r backend/requirements.txt
    startCommand: gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        fromService:
          name: specialwash-frontend
          type: web
          property: url

  - type: web
    name: specialwash-frontend
    runtime: static
    buildCommand: cd specialwash-base-frontend && npm ci && npm run build
    staticPublishPath: specialwash-base-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: specialwash-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
