databases:
  - name: specialwash-db
    plan: free
    region: frankfurt

services:
  - type: web
    name: specialwash-backend
    env: python
    plan: free
    region: frankfurt
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://specialwash-frontend.onrender.com
      - key: FLASK_APP
        value: backend/app.py
    postDeployCommand: "flask db upgrade"

  - type: static
    name: specialwash-frontend
    plan: free
    region: frankfurt
    rootDir: specialwash-base-frontend
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: specialwash-backend
          type: web
          property: url
