databases:
  - name: specialwash-db
    plan: free
    region: frankfurt

services:
  - type: web
    name: specialwash-backend
    env: python
    plan: free
    region: frankfurt
    rootDir: .
    # ⚠️ instala SOLO las deps del backend
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    autoDeploy: true
    postDeployCommand: flask db upgrade
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: backend/app.py
      - key: CORS_ORIGINS
        value: https://specialwash-frontend.onrender.com

  - type: static
    name: specialwash-frontend
    plan: free
    region: frankfurt
    rootDir: specialwash-base-frontend
    buildCommand: npm ci && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: specialwash-backend
          type: web
          property: url
      # opcional, para evitar líos con versiones antiguas de Node:
      - key: NODE_VERSION
        value: "20"
